### ISSUE TITLE
Random segfaults during callbacks

### ISSUE THREAD

**Issue by Casteele72** [flightaware/tclcurl-fa#20]
I am not certain how and when it does, but when setting callbacks for different config options (- writeproc, -debugproc, and -progressproc so far), my installed version will segfault. It is not consistent: I can comment out one callback, and it will work several times and then start segfaulting again. I switch which line is commented out to another callback, and it may work several times before segfaulting again.

My system is Debian 10 (Linux earth 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux).

My TclCurl is from the Debian package repository (tclcurl 7.22.0+hg20160822-2).

I have the following libcurl's installed:
    --  libcurl4 7.64.0-4+deb10u2
    --  libcurl3-gnutls 7.64.0-4+deb10u2
    --  libcurl3-nss 7.64.0-4+deb10u2

TclCurl itself reports:
TclCurl Version 7.22.0 (libcurl/7.64.0 GnuTLS/3.6.7 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3)

I do not know if the package in the Debian package repository is the same as this GitHub codebase. I was unable to successfully compile this one on my system.

My attached script is the start of a script that I plan to use to bulk download the meta-data from several archives from archive.org. It is not complete as I was still in the coding-testing-debuging-morecoding cycle when I encountered this issue. The script ran fine the initial dozen or so times before starting to segfault.

[ia.get-meta.tcl.txt](https://github.com/flightaware/tclcurl-fa/files/7019843/ia.get-meta.tcl.txt)

**Comment by bovine** [comment]
Unfortunately, without a more specific repro test case that is known to occur with this fork of TclCurl, we won't be able to attempt to work on a fix. If you are able to provide more details, or even a pull request with a fix, then we can re-evaluate.
